const menuList=[
    {
        title:'首页',
        key:'/admin/home',
        icon:'home'
    },{
        title:'按钮',
        key:'/admin/ui/button',
        icon:'appstore',
        children:[{
            title:'普通按钮',
            key:'/admin/ui/buttons',
            icon:'appstore',
        },{
            title:'按钮组',
            key:'/admin/ui/group-button',
            icon:'appstore',
        },{
            title:'数据表格',
            key:'/admin/ui/data-table',
            icon:'appstore',
        },{
            title:'表格',
            key:'/admin/ui/table',
            icon:'appstore',
        }]
    },{
        title:'组织管理',
        key:'/admin/org',
        icon:'apartment'
    },{
        title:'用户管理',
        key:'admin/user',
        icon:'user'
    },{
        title:'权限设置',
        key:'/admin/permission',
        icon:'setting'
    }
]
export default menuList